# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_process_pb2 as image__process__pb2


class ImageProcessStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBarcodeInfoFromUrl = channel.unary_unary(
                '/image_process.ImageProcess/GetBarcodeInfoFromUrl',
                request_serializer=image__process__pb2.ImageInfo.SerializeToString,
                response_deserializer=image__process__pb2.BarcodeInfos.FromString,
                )


class ImageProcessServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBarcodeInfoFromUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBarcodeInfoFromUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBarcodeInfoFromUrl,
                    request_deserializer=image__process__pb2.ImageInfo.FromString,
                    response_serializer=image__process__pb2.BarcodeInfos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image_process.ImageProcess', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageProcess(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBarcodeInfoFromUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/image_process.ImageProcess/GetBarcodeInfoFromUrl',
            image__process__pb2.ImageInfo.SerializeToString,
            image__process__pb2.BarcodeInfos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
