# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image-process.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image-process.proto\"\x1e\n\tImageInfo\x12\x11\n\timage_url\x18\x01 \x01(\t\"\xd2\x02\n\x0c\x42\x61rcodeInfos\x12\x30\n\rbarcode_infos\x18\x01 \x03(\x0b\x32\x19.BarcodeInfos.BarcodeInfo\x1a\x8f\x02\n\x0b\x42\x61rcodeInfo\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12,\n\x04rect\x18\x03 \x01(\x0b\x32\x1e.BarcodeInfos.BarcodeInfo.Rect\x12/\n\x06points\x18\x04 \x03(\x0b\x32\x1f.BarcodeInfos.BarcodeInfo.Point\x12\x13\n\x0borientation\x18\x05 \x01(\t\x12\x0f\n\x07quality\x18\x06 \x01(\x05\x1a@\n\x04Rect\x12\x0c\n\x04left\x18\x01 \x01(\x05\x12\x0b\n\x03top\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x1a\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x32=\n\x0cImageProcess\x12-\n\x0egetBarcodeInfo\x12\n.ImageInfo\x1a\r.BarcodeInfos\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_process_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEINFO._serialized_start=23
  _IMAGEINFO._serialized_end=53
  _BARCODEINFOS._serialized_start=56
  _BARCODEINFOS._serialized_end=394
  _BARCODEINFOS_BARCODEINFO._serialized_start=123
  _BARCODEINFOS_BARCODEINFO._serialized_end=394
  _BARCODEINFOS_BARCODEINFO_RECT._serialized_start=299
  _BARCODEINFOS_BARCODEINFO_RECT._serialized_end=363
  _BARCODEINFOS_BARCODEINFO_POINT._serialized_start=365
  _BARCODEINFOS_BARCODEINFO_POINT._serialized_end=394
  _IMAGEPROCESS._serialized_start=396
  _IMAGEPROCESS._serialized_end=457
# @@protoc_insertion_point(module_scope)
